config/routes.rb
KickStarter::Application.routes.draw do

  root :to => 'projects#index'
  resources :projects do
    collection do
      get :top_hits
    end

  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :student
  attr_accessible :email, :student
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :budget, :description, :title, :status
  has_many :students
  validates :title, :presence => true
  validates_numericality_of :budget, on: :create
  scope :ongoing, where(status: 'ongoing')
  scope :completed, where(status: 'completed')
  scope :expensive, where('budget > ?',100)
end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :project
  attr_accessible :name	
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	before_filter :find_project, :except => [:new, :create, :index, :top_hits]
	def new 
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		if @project.save
			redirect_to projects_path
		else
			redirect_to :back
		end
	end

	def index
		@projects = Project.all
		@projects_count = Project.count
	end

	def edit
		#@project=Project.find params[:id]
	end

	def update
			#@project = Project.find params[:id]
			@project.update_attributes params[:project] 
		if @project.save
			redirect_to projects_path
		else
			redirect_to :back
		end
	end

	def destroy
		#@project =Project.find params[:id]
		@project.destroy
		redirect_to projects_path
	end

	def show
		#@project =Project.find params[:id]
	end

	def top_hits
		@projects=Project.expensive
	end

	private
	def find_project
		@project =Project.find params[:id]
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickStarter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f|%>
	<%= f.label :title%>
	<%= f.text_field :title%>
  </br>
	<%= f.label :description%>
	<%= f.text_field :description%>
	</br>
  <%= f.label :abstract%>
	<%= f.text_field :abstract%>
	</br>
  <%= f.label :budget%>
	<%= f.text_field :budget%>
  </br>
  <%=f.submit button_name%>
<%end%>

app/views/projects/edit.html.erb
<h1> This is the edit page </h1>
<h2> Update Project </h2>
<%= render 'form', button_name: 'Update'%>
</br>
</br>
<%=link_to 'Back', projects_path%>

app/views/projects/index.html.erb
<h1> Project is created</h1>
<h2>this is the index page</h2>
Project Count:
<%=@projects_count%>
<h3>Project List</h3>
<%=link_to 'Add Project', new_project_path()%>
<%=link_to 'Top Projects', top_hits_projects_path()%>
<table>
	<tr>
		<td style="color:red" colspan="2">Project Name</td>
		<td   style="color:red" colspan="2">Abstract</td>
	</tr>

<% @projects.each do |project|%>
	<tr>
		<td colspan="2">
		<%=project.title%>
		</td>
		<td colspan="2">
		<%=project.abstract%>
		</td>
		<td colspan="2">
		<%=link_to 'Edit', edit_project_path(project.id)%>
		</td>
		<td colspan="2">
		<%=link_to 'Delete', project_path(project.id), method: 'delete', data: { confirm: 'Are you sure you want to delete?' } %>
		</td>
		<td colspan="2">
		<%=link_to 'Show', project_path(project.id)%>
		</td>
	</tr>
	<%end%>
	
</table>

app/views/projects/new.html.erb
<h1> This is the new page </h1>
<h2> Add new Project </h2>
<%= render 'form', button_name: 'Submit'%>

app/views/projects/show.html.erb
<h1>This is the show page </h1>
		<h2>Title : <%=@project.title%></h2>
		<h2>Description: <%=@project.description%></h2>
		<h2> Abstract: <%=@project.abstract%></h2>
		<h2>Budget: <%=@project.budget%></h2>

app/views/projects/top_hits.html.erb
<table>
	<tr>
		<td style="color:red" colspan="2">Project Name</td>
		<td   style="color:red" colspan="2">Abstract</td>
		<td   style="color:red" colspan="2">Description</td>
		<td   style="color:red" colspan="2">Budget</td>
	</tr>

<% @projects.each do |project|%>
	<tr>
		<td colspan="2">
		<%=project.title%>
		</td>
		<td colspan="2">
		<%=project.abstract%>
		</td>
		<td colspan="2">
		<%=project.description%>
		</td>
		<td colspan="2">
		<%=project.budget%>
		</td>
	</tr>
	<%end%>
	
</table>